server:
  port: 9194
  error:
    whitelabel:
      enabled: true

#Database configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ies_app
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: jainpramodlad@gmail.com
    password: kcosvqiknmkbnhol
    protocol: smtp
    properties:
     mail:
     smtp:
     auth: true
     starttls:
     enable: true
  application:
    name: IES-ADMIN-MODULE
  